"""create images and pairs tables

Revision ID: e099a295d7bb
Revises: 
Create Date: 2026-10-09 13:16:49.034213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e099a295d7bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('credit_source', sa.Text(), nullable=False),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('license_url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_table('pairs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('generator', sa.Text(), nullable=False),
    sa.Column('real_image_id', sa.String(length=32), nullable=False),
    sa.Column('ai_image_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('dataset', 'user')", name=op.f('ck_pairs_source_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_pairs_status_valid')),
    sa.CheckConstraint('real_image_id <> ai_image_id', name=op.f('ck_pairs_real_and_ai_differ')),
    sa.ForeignKeyConstraint(['ai_image_id'], ['images.id'], name=op.f('fk_pairs_ai_image_id_images')),
    sa.ForeignKeyConstraint(['real_image_id'], ['images.id'], name=op.f('fk_pairs_real_image_id_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairs')),
    sa.UniqueConstraint('ai_image_id', name=op.f('uq_pairs_ai_image_id')),
    sa.UniqueConstraint('real_image_id', name=op.f('uq_pairs_real_image_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairs')
    op.drop_table('images')
    # ### end Alembic commands ###
